q_states:
  q_list:
    - '0'
    - '1'
    - '2'
    - '3'
    - '4'
    - '5'
  initial: '0'
  final: '5'

alphabet:
  - 'a'
  - 'b'

tape_alphabet:
  - '#'
  - 'x'

delta:
  - params:
      initial_state: '0'
      mem_cache_value: ''
      tape_input: 'a'
      output:
        final_state: '1'
        mem_cache_value: 'a'
        tape_output: ''
        tape_displacement: 'R'
  - params:
      initial_state: '0'
      mem_cache_value: ''
      tape_input: 'b'
      output:
        final_state: '1'
        mem_cache_value: 'a'
        tape_output: ''
        tape_displacement: 'R'

simulation_strings:
  - 'aab#aab'
  - 'ab#ab'
  - 'abbababa#aba'
